name: Android CI

on:
  release:
    types: [created]
  push:
    branches: [ "release" ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ "release" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew :demo:build
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: APKs
        path: demos/main/buildout/outputs/apk
    - name: Upload the APKs to a release
      if: ${{ github.event_name == 'release' }}
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: |
          demos/main/buildout/outputs/apk/noDecoderExtensions/release/*.apk
          demos/main/buildout/outputs/apk/withDecoderExtensions/release/*.apk
